### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by jyounus** [axldyb/CLLocationManager-blocks#8]
I can't seem to use this in Swift using the bridging header. I get the following problem:

Cannot invoke 'startUpdatingLocationWithUpdateBlock' with an argument list of type '((CLLocationManager, CLLocation, NSError, UnsafeMutablePointer<Bool>) -> Void)'.

The last part "stopUpdate" pointer is causing issues. I tried it with Bool and BOOL datatypes but no luck (as well as without the "UnsafeMutablePointer" part). Anyone have any ideas how to possibly fix this?

Using Swift 1.2 if that makes any difference.

**Comment by axldyb** [comment]
Try this:

```
self.locationManager.startUpdatingLocationWithUpdateBlock { (manager, location, error, stop) in
    NSLog("Loc: %@", location)
    stop.memory = true
}
```
See https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html#//apple_ref/doc/uid/TP40014216-CH8-XID_14 for more information on pointers in Swift. 

Thanks for using the Pod btw :)

**Comment by jyounus** [comment]
I ended up writing my own solution in pure Swift. 

But thanks for your help, maybe it'll help someone else in the future. :)

**Comment by linuxsable** [comment]
@axldyb Thanks for this solution.
