### ISSUE TITLE
Never receive updates with updateLocationAgeFilter set to kCLLocationAgeFilterNone

### ISSUE THREAD

**Issue by GerardJRG** [axldyb/CLLocationManager-blocks#9]
In locationManager:didUpdateLocations: if self.updateLocationAgeFilter is set to kCLLocationAgeFilterNone you'll never get any updates since the check (abs(howRecent) > self.updateLocationAgeFilter) will always be true and you'll hit "continue".  Shouldn't ">" be changed to "<"?

- Gerard

**Comment by axldyb** [comment]
This took some time, but it is fixed now! See version 1.3.3
